CREATE TABLE app_user (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          role VARCHAR(255) NOT NULL,
                          email VARCHAR(255) NOT NULL,
                          name VARCHAR(255) NOT NULL,
                          password VARCHAR(255) NOT NULL,
                          ip VARCHAR(255),
                          status VARCHAR(255) NOT NULL,
                          suspended_until TIMESTAMP(6) WITH TIME ZONE,
                          CONSTRAINT uk_user_email UNIQUE (email)
);

CREATE TABLE supplier (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE product (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(50) NOT NULL,
                         normalized_name VARCHAR(50) NOT NULL,
                         stock INTEGER NOT NULL,
                         price NUMERIC(8,2) NOT NULL,
                         supplier_id BIGINT,
                         cost NUMERIC(8,2) NOT NULL,
                         status VARCHAR(255) NOT NULL,
                         description VARCHAR(500),
                         version BIGINT,
                         CONSTRAINT uk_product_normalized_name UNIQUE (normalized_name),
                         CONSTRAINT fk_product_supplier
                             FOREIGN KEY (supplier_id) REFERENCES supplier(id)
);

CREATE TABLE cart (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      user_id BIGINT NOT NULL UNIQUE,
                      CONSTRAINT fk_cart_user
                          FOREIGN KEY (user_id) REFERENCES app_user(id)
);

CREATE TABLE cart_item (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           cart_id BIGINT NOT NULL,
                           product_id BIGINT NOT NULL,
                           discount NUMERIC(38,2) NOT NULL,
                           price_when_added NUMERIC(8,2) NOT NULL,
                           quantity INTEGER NOT NULL,
                           CONSTRAINT fk_cart_item_cart
                               FOREIGN KEY (cart_id) REFERENCES cart(id),
                           CONSTRAINT fk_cart_item_product
                               FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE shop_order (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            user_id BIGINT NOT NULL,
                            status VARCHAR(255),
                            total NUMERIC(12,2) NOT NULL,
                            stripe_session_id VARCHAR(255) UNIQUE,
                            checkout_url VARCHAR(2048),
                            created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                            expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                            next_recovery_check_at TIMESTAMP(6) WITH TIME ZONE,
                            recovery_lease_until TIMESTAMP(6) WITH TIME ZONE,
                            paid_at TIMESTAMP(6) WITH TIME ZONE,
                            checkout_success_url VARCHAR(2048),
                            checkout_cancel_url VARCHAR(2048),
                            review_needed_at TIMESTAMP(6) WITH TIME ZONE,
                            review_reason VARCHAR(500),
                            review_resolved_at TIMESTAMP(6) WITH TIME ZONE,
                            reviewed_by BIGINT,
                            review_resolution VARCHAR(1000),
                            CONSTRAINT fk_order_user
                                FOREIGN KEY (user_id) REFERENCES app_user(id)
);

CREATE TABLE order_item (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            order_id BIGINT NOT NULL,
                            source_cart_item_id BIGINT,
                            product_id_snapshot BIGINT,
                            product_name_snapshot VARCHAR(255),
                            quantity INTEGER NOT NULL,
                            price NUMERIC(8,2) NOT NULL,
                            line_total NUMERIC(11,2) NOT NULL,
                            CONSTRAINT fk_order_item_order
                                FOREIGN KEY (order_id) REFERENCES shop_order(id)
);